### PR TITLE
changed documentation of usb-c molex connector 

### PR DESCRIPTION
**Pull request by ghost**
added molex docmentation(https://www.molex.com/pdm_docs/ps/1054440001-000.pdf) as Kicad pointed before to a list of generic usb connectors from the usb foundation.

### CODE REVIEW

**Comment by eclecticc** [comment]
Hi, it seems this pull request contains a number of temporary files and other files that aren't related to the proposed change.  Could you adjust the request to only contain the files that need to be modified?

**Comment by ghost** [comment]
I will do it tomorow, i currently don't have access to a computer

**Comment by ghost** [comment]
It should now have been cleaned, feel fre to ask me to change anything else again.

**Comment by ghost** [comment]
@eclecticc the temp files have been removed

**Comment by eclecticc** [comment]
Hi, the remaining changelist doesn't seem to have changes related to the USB-C connector.

**Comment by ghost** [comment]
The problem is that Kicad 6 changed from .sch format to .kicad_sch format and you can't save/export your schematic to .sch. Since Kicad 5 has reached EOL and will be replaced by Kicad 6 or even 7, since they are backward compatible, it would be great if you switched from Kicad 5 to Kicad 6. For most beginners coming from an online guide (like me), Kicad 6 is the standard they learned and practiced with.  I think the best way to allow designers and the framework to exchange designs easily would be to migrate to Kicad 6.

Do you think this is possible, @eclecticc? If not, I would be happy to backport my changes in Kicad 5.

Hope I can get a fast responce

Integrated-circuit

**Pull request closed without merging**
